name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull latest Docker image
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/diplomado:latest

      - name: Stop and remove existing Docker container
        run: |
          docker stop diplomado || true
          docker rm diplomado || true

      - name: Start Docker container
        run: docker run -d --name diplomado -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/diplomado:latest